Ensure that you can run from outside the test directory.
Signed-off-by: Pete Wall <pete.wall@grafana.com>

diff --git a/tools/helm-test/create-cluster b/tools/helm-test/create-cluster
--- a/tools/helm-test/create-cluster
+++ b/tools/helm-test/create-cluster
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -eo pipefail  # Exit immediately if a command fails.
 
 scriptDir=$(dirname "$(readlink -f "$0")")
 source "${scriptDir}/cluster/kind.sh"
@@ -17,8 +18,29 @@ usage() {
   echo "    test-plan.yaml        - The test plan."
 }
 
-testDir=$(pwd)
+# Argument parsing
+if [ "${1}" == "-h" ] || [ "${1}" == "-help" ] || [ "${1}" == "--help" ]; then
+  usage
+  exit 0
+fi
+
+testDir=$1
+
+if [ ! -d "${testDir}" ]; then
+  echo "Argument is not a valid director: ${testDir}"
+  usage
+  exit 1
+fi
+
+testDir=$(realpath "${testDir}")
 testPlan="${testDir}/test-plan.yaml"
+if [ ! -f "${testPlan}" ]; then
+  echo "test-plan.yaml file not found in ${testDir}"
+  usage
+  exit 1
+fi
+
+# Start of script
 clusterName=$(yq eval '.name + "test-cluster"' "${testPlan}")
 clusterType=$(yq eval '.cluster.type' "${testPlan}")
 if [ -z "${clusterType}" ]; then
diff --git a/tools/helm-test/deploy-dependencies b/tools/helm-test/deploy-dependencies
--- a/tools/helm-test/deploy-dependencies
+++ b/tools/helm-test/deploy-dependencies
@@ -1,10 +1,41 @@
 #!/usr/bin/env bash
-
 set -eo pipefail  # Exit immediately if a command fails.
 
 scriptDir=$(dirname "$(readlink -f "$0")")
-fluxDeployed="false"
 
+usage() {
+  echo "USAGE: deploy-dependencies [<test-dir>]"
+  echo ""
+  echo "Deploys dependencies required for testing purposes."
+  echo ""
+  echo "  <test-dir>           - The test directory. Expects this file:"
+  echo "    test-plan.yaml        - The test plan."
+}
+
+# Argument parsing
+if [ "${1}" == "-h" ] || [ "${1}" == "-help" ] || [ "${1}" == "--help" ]; then
+  usage
+  exit 0
+fi
+
+testDir=$1
+
+if [ ! -d "${testDir}" ]; then
+  echo "Argument is not a valid director: ${testDir}"
+  usage
+  exit 1
+fi
+
+testDir=$(realpath "${testDir}")
+testPlan="${testDir}/test-plan.yaml"
+if [ ! -f "${testPlan}" ]; then
+  echo "test-plan.yaml file not found in ${testDir}"
+  usage
+  exit 1
+fi
+
+# Start of script
+fluxDeployed="false"
 deployFluxCD() {
   echo "#### Deploying dependency: FluxCD"
   flux install --components=source-controller,helm-controller 2> /dev/null
@@ -61,12 +92,8 @@ deployTestQueryTest() {
   kubectl apply -f <(yq eval-all 'select(fi == 0) * select(fi == 1) * select(fi == 2)' "${scriptDir}/tests/helmrelease-query-test.yaml" <(echo "${values}") <(echo "${testDependencies}"))
 }
 
-testDir=$(pwd)
-testPlan="${testDir}/test-plan.yaml"
-
 echo; echo "### Deploying dependencies"
 deployFluxCD
-
 dependencyCount=$(yq eval '.dependencies | length - 1' "${testPlan}")
 if [ "${dependencyCount}" -ge 0 ]; then
   for i in $(seq 0 "${dependencyCount}"); do
diff --git a/tools/helm-test/deploy-subject b/tools/helm-test/deploy-subject
--- a/tools/helm-test/deploy-subject
+++ b/tools/helm-test/deploy-subject
@@ -1,10 +1,38 @@
 #!/usr/bin/env bash
-
 set -eo pipefail  # Exit immediately if a command fails.
 
-testDir=$(pwd)
-testPlan="${testDir}/test-plan.yaml"
+usage() {
+  echo "USAGE: deploy-subject [<test-dir>]"
+  echo ""
+  echo "Deploys the Helm chart to be tested."
+  echo ""
+  echo "  <test-dir>           - The test directory. Expects this file:"
+  echo "    test-plan.yaml        - The test plan."
+}
 
+# Argument parsing
+if [ "${1}" == "-h" ] || [ "${1}" == "-help" ] || [ "${1}" == "--help" ]; then
+  usage
+  exit 0
+fi
+
+testDir=$1
+
+if [ ! -d "${testDir}" ]; then
+  echo "Argument is not a valid director: ${testDir}"
+  usage
+  exit 1
+fi
+
+testDir=$(realpath "${testDir}")
+testPlan="${testDir}/test-plan.yaml"
+if [ ! -f "${testPlan}" ]; then
+  echo "test-plan.yaml file not found in ${testDir}"
+  usage
+  exit 1
+fi
+
+# Start of script
 releaseName=$(yq eval '.subject.releaseName // .name' "${testPlan}")
 chartPath=$(yq eval '.subject.path // ""' "${testPlan}")
 if [ -n "${chartPath}" ]; then
diff --git a/tools/helm-test/helm-test b/tools/helm-test/helm-test
--- a/tools/helm-test/helm-test
+++ b/tools/helm-test/helm-test
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
+set -eo pipefail  # Exit immediately if a command fails.
+
+scriptDir=$(dirname "$(readlink -f "$0")")
 
 usage() {
   echo "USAGE: helm-test [<test-dir>]"
@@ -9,11 +12,21 @@ usage() {
   echo "    test-plan.yaml        - The test plan."
 }
 
-set -eo pipefail  # Exit immediately if a command fails.
+# Argument parsing
+if [ "${1}" == "-h" ] || [ "${1}" == "-help" ] || [ "${1}" == "--help" ]; then
+  usage
+  exit 0
+fi
 
-scriptDir=$(dirname "$(readlink -f "$0")")
+testDir=$1
 
-testDir=$(realpath $1)
+if [ ! -d "${testDir}" ]; then
+  echo "Argument is not a valid director: ${testDir}"
+  usage
+  exit 1
+fi
+
+testDir=$(realpath "${testDir}")
 testPlan="${testDir}/test-plan.yaml"
 if [ ! -f "${testPlan}" ]; then
   echo "test-plan.yaml file not found in ${testDir}"
@@ -21,6 +34,7 @@ if [ ! -f "${testPlan}" ]; then
   exit 1
 fi
 
+# Start of script
 CREATE_CLUSTER=${CREATE_CLUSTER:-true}
 if [ "${CREATE_CLUSTER}" == "true" ]; then
   "${scriptDir}/create-cluster" "${testDir}"
diff --git a/tools/helm-test/run-tests b/tools/helm-test/run-tests
--- a/tools/helm-test/run-tests
+++ b/tools/helm-test/run-tests
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -eo pipefail  # Exit immediately if a command fails.
 
 usage() {
   echo "USAGE: run-tests [<test-dir>]"
@@ -9,11 +10,29 @@ usage() {
   echo "    test-plan.yaml        - The test plan."
 }
 
-set -eo pipefail  # Exit immediately if a command fails.
+# Argument parsing
+if [ "${1}" == "-h" ] || [ "${1}" == "-help" ] || [ "${1}" == "--help" ]; then
+  usage
+  exit 0
+fi
 
-testDir=$(pwd)
+testDir=$1
+
+if [ ! -d "${testDir}" ]; then
+  echo "Argument is not a valid director: ${testDir}"
+  usage
+  exit 1
+fi
+
+testDir=$(realpath "${testDir}")
 testPlan="${testDir}/test-plan.yaml"
+if [ ! -f "${testPlan}" ]; then
+  echo "test-plan.yaml file not found in ${testDir}"
+  usage
+  exit 1
+fi
 
+# Start of script
 echo; echo "### Running tests"
 testCount=$(yq eval '.tests | length - 1' "${testPlan}")
 if [ "${testCount}" -ge 0 ]; then
