Add OpenShift support
Signed-off-by: Pete Wall <pete.wall@grafana.com>

diff --git a/tools/helm-test/deploy-dependencies b/tools/helm-test/deploy-dependencies
--- a/tools/helm-test/deploy-dependencies
+++ b/tools/helm-test/deploy-dependencies
@@ -37,11 +37,19 @@ if [ ! -f "${testPlan}" ]; then
 fi
 
 # Start of script
-fluxDeployed="false"
 deployFluxCD() {
   echo "#### Deploying dependency: FluxCD"
-  flux install --components=source-controller,helm-controller 2> /dev/null
-  fluxDeployed="true"
+  clusterType=$(yq eval '.cluster.type // ""' "${testPlan}")
+  if [ "${clusterType}" == "openshift" ]; then
+    fluxManifestFile=$(mktemp /tmp/flux-manifest.yaml.XXXXXX)
+    trap 'rm -f "${fluxManifestFile}"' EXIT  # Ensure the temporary file is removed on exit
+    flux install --components source-controller,helm-controller --export > "${fluxManifestFile}"
+    echo "---" >> "${fluxManifestFile}"
+    curl https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/openshift/scc.yaml >> "${fluxManifestFile}"
+    kubectl apply -f "${fluxManifestFile}"
+  else
+    flux install --components=source-controller,helm-controller 2> /dev/null
+  fi
 }
 
 deployTestParameters() {
@@ -229,28 +237,26 @@ if [ "${testCount}" -ge 0 ]; then
   done
 fi
 
-if [ "${fluxDeployed}" == "true" ]; then
-  echo; echo "### Waiting for Helm releases to be ready"
-  FIVE_MINUTES=300
+echo; echo "### Waiting for Helm releases to be ready"
+FIVE_MINUTES=300
 
-  readyReleases=0
-  helmReleaseCount=$(kubectl get helmreleases --all-namespaces --output name | wc -l | sed 's/^[[:space:]]*//')
-  if [ "${helmReleaseCount}" -gt 0 ]; then
-    for i in $(seq 1 ${FIVE_MINUTES}); do
-      newReadyReleases=$(flux get helmreleases --all-namespaces --status-selector ready=true --no-header | wc -l | sed 's/^[[:space:]]*//')
-      if [ "${readyReleases}" -ne "${newReadyReleases}" ]; then
-        readyReleases="${newReadyReleases}"
-        echo "#### Helm releases ready: ${readyReleases}/${helmReleaseCount}"
-      fi
+readyReleases=0
+helmReleaseCount=$(kubectl get helmreleases --all-namespaces --output name | wc -l | sed 's/^[[:space:]]*//')
+if [ "${helmReleaseCount}" -gt 0 ]; then
+  for i in $(seq 1 ${FIVE_MINUTES}); do
+    newReadyReleases=$(flux get helmreleases --all-namespaces --status-selector ready=true --no-header | wc -l | sed 's/^[[:space:]]*//')
+    if [ "${readyReleases}" -ne "${newReadyReleases}" ]; then
+      readyReleases="${newReadyReleases}"
+      echo "#### Helm releases ready: ${readyReleases}/${helmReleaseCount}"
+    fi
 
-      if [ "${readyReleases}" -ge "${helmReleaseCount}" ]; then break; fi
+    if [ "${readyReleases}" -ge "${helmReleaseCount}" ]; then break; fi
 
-      if [ "${i}" -eq ${FIVE_MINUTES} ]; then
-        echo "A Helm release failed to become ready in ${FIVE_MINUTES} minutes"
-        flux get helmreleases --all-namespaces
-        exit 1
-      fi
-      sleep 1
-    done
-  fi
+    if [ "${i}" -eq ${FIVE_MINUTES} ]; then
+      echo "A Helm release failed to become ready in ${FIVE_MINUTES} minutes"
+      flux get helmreleases --all-namespaces
+      exit 1
+    fi
+    sleep 1
+  done
 fi
