Add the ability to just deploy manifest files
Signed-off-by: Pete Wall <pete.wall@grafana.com>

diff --git a/tools/helm-test/deploy-subject b/tools/helm-test/deploy-subject
--- a/tools/helm-test/deploy-subject
+++ b/tools/helm-test/deploy-subject
@@ -4,7 +4,7 @@ set -eo pipefail  # Exit immediately if a command fails.
 usage() {
   echo "USAGE: deploy-subject [<test-dir>]"
   echo ""
-  echo "Deploys the Helm chart to be tested."
+  echo "Deploys the subject to be tested."
   echo ""
   echo "  <test-dir>           - The test directory. If not provided, the current directory is used."
   echo "                         Expects this file to exist:"
@@ -34,34 +34,13 @@ if [ ! -f "${testPlan}" ]; then
 fi
 
 # Start of script
-releaseName=$(yq eval '.subject.releaseName // .name' "${testPlan}")
+subjectType=$(yq eval '.subject.type // "helm"' "${testPlan}")
+subjectPath=$(yq eval '.subject.path // ""' "${testPlan}")
 
-helmCommand=(helm upgrade --install --wait "${releaseName}")
-helmUpgradeCommand=(helm upgrade --install --wait "${releaseName}")
-
-chart=$(yq eval '.subject.chart // ""' "${testPlan}")
-repository=$(yq eval '.subject.repository // ""' "${testPlan}")
-chartPath=$(yq eval '.subject.path // ""' "${testPlan}")
-
-chartArg=()
-if [ -n "${chart}" ] && [ -n "${repository}" ]; then
-  chartName=$(helm show chart --repo "${repository}" "${chart}" | yq .name)
-  chartArg=(--repo "${repository}" "${chart}")
-fi
-
-if [ -n "${chartPath}" ]; then
-  if ! grep "^oci://" <<< "${chartPath}" > /dev/null; then
-    chartPath=$(realpath "${testDir}/${chartPath}")
-  fi
-  chartName=$(helm show chart "${chartPath}" | yq .name)
-  chartArg=("${chartPath}")
-fi
-
-versionArg=()
-chartVersion=$(yq eval '.subject.version // ""' "${testPlan}")
-if [ -n "${chartVersion}" ]; then
-  versionArg=(--version "${chartVersion}")
-fi
+extraArgs=()
+for arg in $(yq eval -r '.subject.extraArgs[] // ""' "${testPlan}"); do
+  extraArgs+=("${arg}")
+done
 
 # Check for a namespace
 namespaceArg=()
@@ -70,37 +49,69 @@ if [ -n "${releaseNamespace}" ]; then
   namespaceArg=(--namespace "${releaseNamespace}" --create-namespace)
 fi
 
-# Check for values that are defined directly in the test plan
-valuesArg=()
-chartValues=$(yq eval '.subject.values // ""' "${testPlan}")
-if [ -n "${chartValues}" ]; then
-  valuesFile=$(mktemp /tmp/values.yaml.XXXXXX)
-  trap 'rm -f "${valuesFile}"' EXIT  # Ensure the temporary file is removed on exit
-  echo "${chartValues}" > "${valuesFile}"
-  valuesArg=(-f "${valuesFile}")
-fi
+if [ "${subjectType}" == "manifest" ]; then
+  echo; echo "### Deploying manifest: ${subjectPath}"
+  subjectPath=$(realpath "${testDir}/${subjectPath}")
+  applyCommand=(kubectl apply -f "${subjectPath}" "${namespaceArg[@]}" "${extraArgs[@]}")
+  echo "${applyCommand[@]}"
+  "${applyCommand[@]}"
+elif [ "${subjectType}" == "helm" ]; then
+  releaseName=$(yq eval '.subject.releaseName // .name' "${testPlan}")
 
-# Check for a values file
-chartValuesFile=$(yq eval '.subject.valuesFile // ""' "${testPlan}")
-if [ -n "${chartValuesFile}" ]; then
-  chartValuesFile=$(realpath "${testDir}/${chartValuesFile}")
-  if [ -f "${chartValuesFile}" ]; then
-    valuesArg=(-f "${chartValuesFile}")
-  else
-    echo "Upgrade values file not found: ${chartValuesFile}."
-    exit 1
+  helmCommand=(helm upgrade --install --wait "${releaseName}")
+  helmUpgradeCommand=(helm upgrade --install --wait "${releaseName}")
+
+  chart=$(yq eval '.subject.chart // ""' "${testPlan}")
+  repository=$(yq eval '.subject.repository // ""' "${testPlan}")
+
+  chartArg=()
+  if [ -n "${chart}" ] && [ -n "${repository}" ]; then
+    chartName=$(helm show chart --repo "${repository}" "${chart}" | yq .name)
+    chartArg=(--repo "${repository}" "${chart}")
   fi
-fi
 
-# Run the helm command
-echo; echo "### Deploying Helm chart: ${chartName}"
-helmCommand+=("${chartArg[@]}" "${versionArg[@]}" "${namespaceArg[@]}" "${valuesArg[@]}")
-extraArgs=$(yq eval -r '.subject.extraArgs[] // ""' "${testPlan}")
-for arg in ${extraArgs}; do
-  helmCommand+=("${arg}")
-done
-echo "${helmCommand[@]}"
-"${helmCommand[@]}"
+  if [ -n "${subjectPath}" ]; then
+    if ! grep "^oci://" <<< "${subjectPath}" > /dev/null; then
+      subjectPath=$(realpath "${testDir}/${subjectPath}")
+    fi
+    chartName=$(helm show chart "${subjectPath}" | yq .name)
+    chartArg=("${subjectPath}")
+  fi
+
+  versionArg=()
+  chartVersion=$(yq eval '.subject.version // ""' "${testPlan}")
+  if [ -n "${chartVersion}" ]; then
+    versionArg=(--version "${chartVersion}")
+  fi
+
+  # Check for values that are defined directly in the test plan
+  valuesArg=()
+  chartValues=$(yq eval '.subject.values // ""' "${testPlan}")
+  if [ -n "${chartValues}" ]; then
+    valuesFile=$(mktemp /tmp/values.yaml.XXXXXX)
+    trap 'rm -f "${valuesFile}"' EXIT  # Ensure the temporary file is removed on exit
+    echo "${chartValues}" > "${valuesFile}"
+    valuesArg=(-f "${valuesFile}")
+  fi
+
+  # Check for a values file
+  chartValuesFile=$(yq eval '.subject.valuesFile // ""' "${testPlan}")
+  if [ -n "${chartValuesFile}" ]; then
+    chartValuesFile=$(realpath "${testDir}/${chartValuesFile}")
+    if [ -f "${chartValuesFile}" ]; then
+      valuesArg=(-f "${chartValuesFile}")
+    else
+      echo "Upgrade values file not found: ${chartValuesFile}."
+      exit 1
+    fi
+  fi
+
+  # Run the helm command
+  echo; echo "### Deploying Helm chart: ${chartName}"
+  helmCommand+=("${chartArg[@]}" "${versionArg[@]}" "${namespaceArg[@]}" "${valuesArg[@]}" "${extraArgs[@]}")
+  echo "${helmCommand[@]}"
+  "${helmCommand[@]}"
+fi
 
 # Run post-install options
 postInstallFilesCount=$(yq eval '.subject.postInstall.files | length - 1' "${testPlan}")
@@ -118,49 +129,50 @@ if [ "${postInstallFilesCount}" -ge 0 ]; then
   done
 fi
 
-
-upgradeValues=$(yq eval '.subject.upgrade.values // ""' "${testPlan}")
-upgradeValuesFile=$(yq eval '.subject.upgrade.valuesFile // ""' "${testPlan}")
-upgradeVersion=$(yq eval '.subject.upgrade.version // ""' "${testPlan}")
-upgradePath=$(yq eval '.subject.upgrade.path // ""' "${testPlan}")
-if [ -n "${upgradeValues}" ] || [ -n "${upgradeValuesFile}" ] || [ -n "${upgradeVersion}" ] || [ -n "${upgradePath}" ]; then
-  # Check for values that are defined directly in the test plan
-  if [ -n "${upgradeValues}" ]; then
-    valuesFile=$(mktemp /tmp/values.yaml.XXXXXX)
-    trap 'rm -f "${valuesFile}"' EXIT  # Ensure the temporary file is removed on exit
-    echo "${upgradeValues}" > "${valuesFile}"
-    valuesArg=(-f "${valuesFile}")
-  fi
-
-  # Check for a values file
-  if [ -n "${upgradeValuesFile}" ]; then
-    upgradeValuesFile=$(realpath "${testDir}/${upgradeValuesFile}")
-    if [ -f "${upgradeValuesFile}" ]; then
-      valuesArg=(-f "${upgradeValuesFile}")
-    else
-      echo "Upgrade values file not found: ${upgradeValuesFile}."
-      exit 1
+if [ "${subjectType}" == "helm" ]; then
+  upgradeValues=$(yq eval '.subject.upgrade.values // ""' "${testPlan}")
+  upgradeValuesFile=$(yq eval '.subject.upgrade.valuesFile // ""' "${testPlan}")
+  upgradeVersion=$(yq eval '.subject.upgrade.version // ""' "${testPlan}")
+  upgradePath=$(yq eval '.subject.upgrade.path // ""' "${testPlan}")
+  if [ -n "${upgradeValues}" ] || [ -n "${upgradeValuesFile}" ] || [ -n "${upgradeVersion}" ] || [ -n "${upgradePath}" ]; then
+    # Check for values that are defined directly in the test plan
+    if [ -n "${upgradeValues}" ]; then
+      valuesFile=$(mktemp /tmp/values.yaml.XXXXXX)
+      trap 'rm -f "${valuesFile}"' EXIT  # Ensure the temporary file is removed on exit
+      echo "${upgradeValues}" > "${valuesFile}"
+      valuesArg=(-f "${valuesFile}")
     fi
-  fi
 
-  if [ -n "${upgradeVersion}" ]; then
-    versionArg=(--version "${upgradeVersion}")
-  fi
-
-  if [ -n "${upgradePath}" ]; then
-    if ! grep "^oci://" <<< "${upgradePath}" > /dev/null; then
-      upgradePath=$(realpath "${testDir}/${upgradePath}")
+    # Check for a values file
+    if [ -n "${upgradeValuesFile}" ]; then
+      upgradeValuesFile=$(realpath "${testDir}/${upgradeValuesFile}")
+      if [ -f "${upgradeValuesFile}" ]; then
+        valuesArg=(-f "${upgradeValuesFile}")
+      else
+        echo "Upgrade values file not found: ${upgradeValuesFile}."
+        exit 1
+      fi
     fi
-    chartArg=("${upgradePath}")
-  fi
 
-  # Run the helm upgrade command
-  echo; echo "### Upgrading Helm chart: ${chartName}"
-  helmUpgradeCommand+=("${chartArg[@]}" "${versionArg[@]}" "${namespaceArg[@]}" "${valuesArg[@]}")
-  extraArgs=$(yq eval -r '.subject.upgrade.extraArgs[] // ""' "${testPlan}")
-  for arg in ${extraArgs}; do
-    helmUpgradeCommand+=("${arg}")
-  done
-  echo "${helmUpgradeCommand[@]}"
-  "${helmUpgradeCommand[@]}"
+    if [ -n "${upgradeVersion}" ]; then
+      versionArg=(--version "${upgradeVersion}")
+    fi
+
+    if [ -n "${upgradePath}" ]; then
+      if ! grep "^oci://" <<< "${upgradePath}" > /dev/null; then
+        upgradePath=$(realpath "${testDir}/${upgradePath}")
+      fi
+      chartArg=("${upgradePath}")
+    fi
+
+    # Run the helm upgrade command
+    echo; echo "### Upgrading Helm chart: ${chartName}"
+    helmUpgradeCommand+=("${chartArg[@]}" "${versionArg[@]}" "${namespaceArg[@]}" "${valuesArg[@]}")
+    extraArgs=$(yq eval -r '.subject.upgrade.extraArgs[] // ""' "${testPlan}")
+    for arg in ${extraArgs}; do
+      helmUpgradeCommand+=("${arg}")
+    done
+    echo "${helmUpgradeCommand[@]}"
+    "${helmUpgradeCommand[@]}"
+  fi
 fi
