Add the ability to skip the flux deployment (#158)
Signed-off-by: Pete Wall <pete.wall@grafana.com>

diff --git a/tools/helm-test/deploy-dependencies b/tools/helm-test/deploy-dependencies
--- a/tools/helm-test/deploy-dependencies
+++ b/tools/helm-test/deploy-dependencies
@@ -171,7 +171,10 @@ deployTestRemotecfgComponentsTest() {
 }
 
 echo; echo "### Deploying dependencies"
-deployFluxCD
+deployFlux=$(yq eval '.deployFlux // true' "${testPlan}")
+if [ "${deployFlux}" == "true" ]; then
+  deployFluxCD
+fi
 kubectl apply -f "${scriptDir}/manifests/tests/namespace-toolbox.yaml"
 
 dependencyCount=$(yq eval '.dependencies | length - 1' "${testPlan}")
@@ -313,26 +316,28 @@ if [ "${testCount}" -ge 0 ]; then
   done
 fi
 
-echo; echo "### Waiting for Helm releases to be ready"
-FIVE_MINUTES=300
+if [ "${deployFlux}" == "true" ]; then
+  echo; echo "### Waiting for Helm releases to be ready"
+  FIVE_MINUTES=300
 
-readyReleases=0
-helmReleaseCount=$(kubectl get helmreleases --all-namespaces --output name | wc -l | sed 's/^[[:space:]]*//')
-if [ "${helmReleaseCount}" -gt 0 ]; then
-  for i in $(seq 1 ${FIVE_MINUTES}); do
-    newReadyReleases=$(flux get helmreleases --all-namespaces --status-selector ready=true --no-header | wc -l | sed 's/^[[:space:]]*//')
-    if [ "${readyReleases}" -ne "${newReadyReleases}" ]; then
-      readyReleases="${newReadyReleases}"
-      echo "#### Helm releases ready: ${readyReleases}/${helmReleaseCount}"
-    fi
+  readyReleases=0
+  helmReleaseCount=$(kubectl get helmreleases --all-namespaces --output name | wc -l | sed 's/^[[:space:]]*//')
+  if [ "${helmReleaseCount}" -gt 0 ]; then
+    for i in $(seq 1 ${FIVE_MINUTES}); do
+      newReadyReleases=$(flux get helmreleases --all-namespaces --status-selector ready=true --no-header | wc -l | sed 's/^[[:space:]]*//')
+      if [ "${readyReleases}" -ne "${newReadyReleases}" ]; then
+        readyReleases="${newReadyReleases}"
+        echo "#### Helm releases ready: ${readyReleases}/${helmReleaseCount}"
+      fi
 
-    if [ "${readyReleases}" -ge "${helmReleaseCount}" ]; then break; fi
+      if [ "${readyReleases}" -ge "${helmReleaseCount}" ]; then break; fi
 
-    if [ "${i}" -eq ${FIVE_MINUTES} ]; then
-      echo "A Helm release failed to become ready in ${FIVE_MINUTES} minutes"
-      flux get helmreleases --all-namespaces
-      exit 1
-    fi
-    sleep 1
-  done
+      if [ "${i}" -eq ${FIVE_MINUTES} ]; then
+        echo "A Helm release failed to become ready in ${FIVE_MINUTES} minutes"
+        flux get helmreleases --all-namespaces
+        exit 1
+      fi
+      sleep 1
+    done
+  fi
 fi
