More path work
Signed-off-by: Pete Wall <pete.wall@grafana.com>

diff --git a/tools/helm-test/deploy-dependencies b/tools/helm-test/deploy-dependencies
--- a/tools/helm-test/deploy-dependencies
+++ b/tools/helm-test/deploy-dependencies
@@ -107,21 +107,25 @@ if [ "${dependencyCount}" -ge 0 ]; then
 
     dependencyDirectory=$(yq eval ".dependencies[${i}].directory // \"\"" "${testPlan}")
     if [ -n "${dependencyDirectory}" ]; then
+      dependencyDirectory=$(realpath "${testDir}/${dependencyDirectory}")
       if [ -d "${dependencyDirectory}" ]; then
         echo "#### Deploying dependency by directory: ${dependencyDirectory}"
-        kubectl apply -f "${testDir}/${dependencyDirectory}"
+        kubectl apply -f "${dependencyDirectory}"
       else
-        echo "Dependency directory not found: ${dependencyDirectory}. Skipping."
+        echo "Dependency directory not found: ${dependencyDirectory}."
+        exit 1
       fi
     fi
 
     dependencyFile=$(yq eval ".dependencies[${i}].file // \"\"" "${testPlan}")
     if [ -n "${dependencyFile}" ]; then
+      dependencyFile=$(realpath "${testDir}/${dependencyFile}")
       if [ -f "${dependencyFile}" ]; then
         echo "#### Deploying dependency by file: ${dependencyFile}"
-        kubectl apply -f "${testDir}/${dependencyFile}"
+        kubectl apply -f "${dependencyFile}"
       else
-        echo "Dependency file not found: ${dependencyFile}. Skipping."
+        echo "Dependency file not found: ${dependencyFile}."
+        exit 1
       fi
     fi
 
@@ -146,7 +150,8 @@ if [ "${testCount}" -ge 0 ]; then
     testType=$(yq eval ".tests[${i}].type" "${testPlan}")
     if [ "${testType}" == "query-test" ]; then deployTestQueryTest "${i}";
     else
-      echo "Unknown test type: ${testType}. Skipping."
+      echo "Unknown test type: ${testType}."
+      exit 1
     fi
   done
 fi
diff --git a/tools/helm-test/deploy-subject b/tools/helm-test/deploy-subject
--- a/tools/helm-test/deploy-subject
+++ b/tools/helm-test/deploy-subject
@@ -36,12 +36,13 @@ fi
 releaseName=$(yq eval '.subject.releaseName // .name' "${testPlan}")
 chartPath=$(yq eval '.subject.path // ""' "${testPlan}")
 if [ -n "${chartPath}" ]; then
-  chartName=$(helm show chart "${testDir}/${chartPath}" | yq .name)
+  chartPath=$(realpath "${testDir}/${chartPath}")
+  chartName=$(helm show chart "${chartPath}" | yq .name)
 ## TODO handle chartRepo, chart, and chartVersion for remote installation
 fi
 
-helmCommand=(helm upgrade --install --wait "${releaseName}" "${testDir}/${chartPath}")
-helmUpgradeCommand=(helm upgrade --install --wait "${releaseName}" "${testDir}/${chartPath}")
+helmCommand=(helm upgrade --install --wait "${releaseName}" "${chartPath}")
+helmUpgradeCommand=(helm upgrade --install --wait "${releaseName}" "${chartPath}")
 
 # Check for a namespace
 releaseNamespace=$(yq eval '.subject.namespace // ""' "${testPlan}")
@@ -62,7 +63,13 @@ fi
 # Check for a values file
 chartValuesFile=$(yq eval '.subject.valuesFile // ""' "${testPlan}")
 if [ -n "${chartValuesFile}" ]; then
-  helmCommand+=(-f "${testDir}/${chartValuesFile}")
+  chartValuesFile=$(realpath "${testDir}/${chartValuesFile}")
+  if [ -f "${chartValuesFile}" ]; then
+    helmUpgradeCommand+=(-f "${chartValuesFile}")
+  else
+    echo "Upgrade values file not found: ${chartValuesFile}."
+    exit 1
+  fi
 fi
 
 # Run the helm command
@@ -75,8 +82,14 @@ postInstallFilesCount=$(yq eval '.subject.postInstall.files | length - 1' "${tes
 if [ "${postInstallFilesCount}" -ge 0 ]; then
   for i in $(seq 0 "${postInstallFilesCount}"); do
     postInstallFile=$(yq eval ".subject.postInstall.files[${i}]" "${testPlan}")
-    echo "#### Deploying Post-install manifest: ${postInstallFile}"
-    kubectl apply -f "${testDir}/${postInstallFile}"
+    postInstallFile=$(realpath "${testDir}/${postInstallFile}")
+    if [ -f "${postInstallFile}" ]; then
+      echo "#### Deploying Post-install manifest: ${postInstallFile}"
+      kubectl apply -f "${testDir}/${postInstallFile}"
+    else
+      echo "Post-install file not found: ${postInstallFile}."
+      exit 1
+    fi
   done
 fi
 
@@ -96,7 +109,13 @@ if [ -n "${upgradeValues}" ] || [ -n "${upgradeValuesFile}" ]; then
 
   # Check for a values file
   if [ -n "${upgradeValuesFile}" ]; then
-    helmUpgradeCommand+=(-f "${testDir}/${upgradeValuesFile}")
+    upgradeValuesFile=$(realpath "${testDir}/${upgradeValuesFile}")
+    if [ -f "${upgradeValuesFile}" ]; then
+      helmUpgradeCommand+=(-f "${upgradeValuesFile}")
+    else
+      echo "Upgrade values file not found: ${upgradeValuesFile}."
+      exit 1
+    fi
   fi
 
   # Run the helm upgrade command
